version: "3.8"
services:
  da3em_app:
    container_name: da3em_app
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 9000
    volumes:
      - .:/usr/src/app
      - ./public:/usr/src/app/public
    networks:
      - app_network

  da3em_nginx:
    container_name: da3em_nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
    - ./public:/usr/src/app/public
    ports:
      - 8000:80
    depends_on:
      - da3em_app
    environment:
      NGINX_FPM_HOST: da3em_app
      NGINX_ROOT: /usr/src/app/public
    networks:
      - app_network

  

  blog_redis:
    container_name: da3em_redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app_network

networks:
  app_network:
    driver: bridge