version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:1vaU3dfc+sWjx8TuDXzginRsEa2dp2SBL+Ujs6QCb5c=
      - DB_HOST=your_ovh_db_host      # Replace with your OVH database host
      - DB_PORT=3306
      - DB_DATABASE=nichen            # Use your actual database name
      - DB_USERNAME=nichen            # Use your actual database username
      - DB_PASSWORD=n1ch3n            # Use your actual database password

  web:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
